### ISSUE TITLE
Not installing all requirements

### ISSUE THREAD

**Issue by nerfpops** [lean-delivery/ansible-role-solr-standalone#31]
This:
```
- name: Install requirements
  package:
    name: '{{ requirements }}'
    state: present
  register: installed_packages
  until: installed_packages is succeeded
become: True
```

should be changed to this, to support multiple requirements:
```
- name: Install requirements
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ requirements }}'
  register: installed_packages
  until: installed_packages is succeeded
  become: True
```
