### ISSUE TITLE
Services running via systemd do not have ulimits applied

### ISSUE THREAD

**Issue by ccheline** [lean-delivery/ansible-role-solr-standalone#34]
##### SUMMARY
The SOLR service started by systemd alerts that limits are not set properly.
systemd ignores /etc/security/limits, so the limits must be added to the systemd configuration.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

templates/solr.service.j2

##### ANSIBLE VERSION

```
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 08:02:28) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39.0.1)]
```

##### CONFIGURATION

DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['ini']

##### OS / ENVIRONMENT

Source and Destination: Oracle Linux Server release 7.7

##### STEPS TO REPRODUCE

```yaml
- name: Install and Configure Solr Servers without ssl and authentication
  hosts: solrcloud
  vars:
    solr_version: 8.4.1
    solr_use_java_version_8: false
    solr_set_limits: true
    solr_open_files_limit: 65000
    solr_max_processes_limit: 65000
    solr_change_default_password: False
    solr_auth_configure: False
    solr_ssl_configure: False
    solr_insh_default: "{{ solr_dest_path }}/bin/solr.in.sh"
    zk_inventory_group: zk_development
    zk_hosts_list: '{{ groups[zk_inventory_group] | list }}'
    configset_list:
      - default
    auto_populate_configset_list: True
    zk_enable_ssl: False

  roles:
    - role: lean_delivery.java
    - role: lean_delivery.solr_standalone
    - role: lean_delivery.solr_cloud
```

##### EXPECTED RESULTS

SOLR installation and startup without errors or warnings.

##### ACTUAL RESULTS

SOLR installation and startup with the following warning (/var/log/messages):

```
Mar 12 16:39:47 SERVER systemd: Started Solr service.
Mar 12 16:39:47 SERVER solr: *** [WARN] *** Your open file limit is currently 1024.
Mar 12 16:39:47 SERVER solr: It should be set to 65000 to avoid operational disruption.
Mar 12 16:39:47 SERVER solr: If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
Mar 12 16:39:47 SERVER solr: *** [WARN] ***  Your Max Processes Limit is currently 14981.
Mar 12 16:39:47 SERVER solr: It should be set to 65000 to avoid operational disruption.
Mar 12 16:39:47 SERVER solr: If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
```
