### ISSUE TITLE
Add ability to download solr archive from private AWS S3 bucket

### ISSUE THREAD

**Issue by DmitriyStoyanov** [lean-delivery/ansible-role-solr-standalone#42]
##### SUMMARY

Right now we face with downloading issues because of limits on their side
https://archive.apache.org/
Do note that heavy use of this service will result in immediate throttling of your download speeds to either 12 or 6 mbps for the remainder of the day, depending on severity. Continuous abuse (to the tune of more than 40 GB downloaded per week) will cause an [automatic ban](https://infra.apache.org/infra-ban.html), so please tune your services to this fact.

So we tried to increase timeout here: #41
But no luck. On of the solution to copy file to s3 bucket and then pull from that place.

So we need to have option to download solr binary via s3 instead of public url

##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

```yaml
- name: Install and customize Solr
  hosts:
    - solr
  roles:
    - role: lean_delivery.solr_standalone
      vars:
        solr_version: 8.11.4
        solr_url: https://soms3bucketname.s3.amazonaws.com/solr
        solr_ssl_configure: false
        solr_auth_configure: false
        solr_change_default_password: false
```

##### EXPECTED RESULTS

File is downloaded from s3

##### ACTUAL RESULTS

TASK [lean_delivery.solr_standalone : Get sha512 for solr 8.11.4] *******************************************************************************************************************
fatal: [i-xxxxxxx]: FAILED! => {"msg": "Received HTTP error for https://xxxxx.s3.amazonaws.com/solr/8.11.4/solr-8.11.4.zip.sha512 : HTTP Error 403: Forbidden"}

```

```

**Comment by DmitriyStoyanov** [comment]
Sample of existing part downloading s3
```yaml
- name: Install pip packages needed by Ansible aws_s3
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
    extra_args: '--upgrade'
  register: install_packages
  until: install_packages is succeeded
  become: true

- name: Download solr_customizations artifact from s3
  amazon.aws.aws_s3:
    bucket: "{{ bucket_name }}"
    object: "{{ solr_customizations }}"
    dest: "/tmp/{{ solr_customizations }}"
    mode: get
  become: true
```

So possibly we can use similar approach here with appropriate change to add the option
